# RAG Ingestion Configuration
# Windows-first configuration for local ChromaDB RAG system

ingestion:
  # Target file types for ingestion
  file_types:
    - ".md"
    - ".pdf"
    - ".json"

  # Text chunking configuration
  chunking:
    # Target chunk size in tokens (200-500 range recommended)
    chunk_size: 350
    # Overlap between chunks as percentage of chunk_size (20% recommended)
    overlap_percent: 0.2
    # Token encoding model for accurate token counting
    encoding_model: "cl100k_base"  # GPT-3.5/4 tokenizer

  # Embedding configuration
  embedding:
    # Local sentence transformer model
    model_name: "all-MiniLM-L6-v2"
    # Device for embedding computation (cpu for Windows compatibility)
    device: "cpu"
    # Batch size for embedding generation
    batch_size: 32

  # ChromaDB configuration
  chroma:
    # Collection name for knowledge base
    collection_name: "knowledge_base"
    # Persistence directory (relative to rag/ directory)
    persist_directory: "store"
    # Metadata to include with each document
    metadata_fields:
      - "source_file"
      - "file_type"
      - "chunk_index"
      - "total_chunks"
      - "ingestion_timestamp"

  # File processing settings
  processing:
    # Maximum file size to process (in MB)
    max_file_size_mb: 50
    # Encoding for text files
    text_encoding: "utf-8"
    # Skip hidden files and directories
    skip_hidden: true
    # Skip files matching these patterns
    skip_patterns:
      - "*.tmp"
      - "*.bak"
      - ".DS_Store"
      - "Thumbs.db"

# File watching configuration for auto_ingest.ps1
watching:
  # Directory to watch for changes
  watch_directory: "knowledge"
  # File change events to monitor
  watch_events:
    - "created"
    - "modified"
    - "deleted"
  # Patterns to watch within directory
  watch_patterns:
    - "*.md"
    - "*.pdf"
    - "*.json"
  # Ignore patterns
  ignore_patterns:
    - "*.tmp"
    - "*.bak"
    - ".DS_Store"
    - "Thumbs.db"
  # Debounce delay in seconds (avoid rapid re-processing)
  debounce_seconds: 2

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "rag_ingest.log"
