name: quality
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        run: python - <<'PY'
import json; json.load(open('.cursor/mcp.json'))
PY
      - name: Scan for conflict markers
        run: |
          if git grep -nE '^(<<<<<<<|=======|>>>>>>>)' -- .; then
            echo 'Unresolved conflicts found'; exit 1; fi
      - name: Python smoke test
        run: python - <<'PY'
import sys
sys.path.insert(0, '.cursor')
from mcp.server import MCPServer
server = MCPServer()
print('IMPORT_OK')
PY
